language: python
python:
    - "3.6"

# Install dependencies
install:
    - pip3 install -r requirements.txt
    - pip3 install coveralls

services:
    - postgresql

before_script:
    - psql -c 'CREATE DATABASE test_quizer_db;' -U postgres

# Run tests
script:
     - pytest --cov=app

after_success:
    - coveralls
#
# branches:
#     only:
#         - develop