#Language specification
language: python
python:
  - "3.6.7"
# Installing dependencies
services:
  - postgresql
install: 
  - pip install -r requirements.txt
  - pip install coveralls
before_script:
  - psql -c "CREATE DATABASE quizer_test_db;" -U postgres
# Running tests
script: 
  - pytest --cov=app
after_success:
  - coveralls